language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester tests -s

jobs:
  include:
    - name: Nette Code Checker
      install:
        - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
      script:
        - php temp/code-checker/code-checker --strict-types


    - name: Nette Coding Standard
      install:
        - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
      script:
        - php temp/coding-standard/ecs check src tests --config temp/coding-standard/coding-standard-php71.yml


    - stage: Code Coverage
      script:
        - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config tests/.coveralls.yml
