language: php
php:
  - 7.4

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

jobs:
  include:
    - name: Nette Code Checker
      install:
        - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
      script:
        - php temp/code-checker/code-checker --strict-types


    - name: Static Analysis
      script:
        - composer run-script phpstan


    - stage: Nette Tester
      install:
        - travis_retry composer require nette/tester --dev
      script:
        - composer run-script tester


    - stage: Code Coverage
      script:
        - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config tests/.coveralls.yml
